export const NavbarMenu = [
  {
    name: "Home",
    url: "/",
  },
  {
    name: "Career therapy",
    url: "/therapy",
  },
  {
    name: "About us",
    url: "/about",
  },
  {
    name: "Career Resources",
    url: "/job",
  },
  {
    name: "FAQs",
    url: "/faq",
  },
];

export const CAREERTHERAPYSERVICE = [
  {
    name: "Career coaching",
    url: "/therapy",
    text: "Let’s meet one-on-one and outline a plan to negotiate a higher salary, resolve a conflict with a colleague, strategize your next move or figure out what you really want to do when you grow up.",
    rate: "$100/Hour",
  },
  {
    name: "Interview and Salary Negotiation",
    url: "/therapy",
    text: "Did you know only 20% of job candidates negotiate their hiring offers? That means most people in the market are leaving money on the table. Don’t be one of them. We’ll get you ready for interviews that get the offer you deserve and the salary you desire.",
    rate: "$75/Hour",
  },
  {
    name: "Job Search Support",
    url: "/therapy",
    text: "Internet searches may not be enough to discover your next amazing career opportunity or prepare you to get it. Does your resume stand out? Are your cover letters selling your skills? Let us get you all ready to outshine the competition and receive the offer letter you want.",
    rate: "$75/Hour",
  },
  {
    name: "Work 101 Webinar",
    url: "/therapy",
    text: "Our one-hour seminar for recent graduates entering the job market is packed with inside corporate do’s and don’ts we wish we’d known when we were starting our careers. Designed specifically for young Black professionals, you’ll learn how to flourish in your first role, navigate office politics, and position yourself for promotions and growth.",
    rate: "$50/Access ",
  },
];

export const FAQs = [
  {
    name: "What Is The Onyx Truth?",
    answer:
      "The Onyx Truth is an anonymous place for Black professionals to come together to share insights on their workplace experiences.",
  },
  {
    name: "Is The Onyx Truth Platform Free?",
    answer:
      "Yes. It is free to sign up on The Onyx Truth and share insights about workplace culture for free.",
  },
  {
    name: "Who Can Use The Onyx Truth?",
    answer:
      "This platform was designed for Black Professionals from all feilds and industries.",
  },
  {
    name: "Is The Onyx Truth Anonymous?",
    answer: "Yes. This platform runs on full anonymity.",
  },
  {
    name: "How Does The Onyx Truth Protect The Identity Of Users",
    answer:
      "(a) Email registered during registration will not be shared on The Onyx Board.</br> (b)Companies with less than five reviews will not display open-ended feedback </br> (c) Data cannot be segmented for companies with less than five reviews",
  },
  {
    name: "What Is The Onyx Score?",
    answer:
      "We put out an extensive list of questions to glean insights on the Black experience in the workplace. The results from the close-ended questions will be weighted, and each company will receive a composite Onyx Score",
  },
  {
    name: "What Other Services Can I Get On The Onyx Truth?",
    answer:
      "The Professional Diversity Network—a group that includes Women’s Career Channel, Pride Careers and Ability Careers—sources a database of qualified candidates and hosts in-person career events all over the country.",
  },
  {
    name: "What Is Career Therapy?",
    answer:
      "The Professional Diversity Network—a group that includes Women’s Career Channel, Pride Careers and Ability Careers—sources a database of qualified candidates and hosts in-person career events all over the country.",
  },
  {
    name: "What Services Does The Career Therapy Cover?",
    answer:
      "Career Therapy covers services like Career Coaching, Resume Review, Mock Interviews, Linkedin Services, and exclusive access to Career Resources.",
  },
  {
    name: "Is Career Therapy Free?",
    answer:
      "The cost of Career Therapy is dependent on many factors, such as your experience, goals, and the services you need.",
  },
];

export const SexOptions = [
  { value: "asexual", label: "Asexual" },
  { value: "bisexual", label: "Bisexual" },
  { value: "gay", label: "Gay" },
  { value: "hetrosexual", label: "Hetrosexual" },
  { value: "straight", label: "Straight" },
];
export const IdentifyOptions = [
  { value: "male", label: "Male" },
  { value: "female", label: "Female" },
  { value: "transgender", label: "Transgender" },
  { value: "self-identify", label: "Self-Describe ( Please Specify ) " },
];
// export const EmploymentOptions = [
//     { value: 'Accounting', label: 'Accounting' },
//     { value: 'Airlines/Aviation', label: 'Airlines/Aviation' },
//     { value: 'Alternative Dispute Resolution', label: 'Alternative Dispute Resolution' },
//     { value: 'Alternative Medicine', label: 'Alternative Medicine' },
//     { value: 'Animation', label: 'Animation' },
//     { value: 'Apparel/Fashion', label: 'Apparel/Fashion' },
//     { value: 'Architecture/Planning', label: 'Architecture/Planning' },
// ];

export const EmploymentOptions = [
  { value: "Industry", label: "Industry" },
  { value: "Accounting", label: "Accounting" },
  { value: "Airlines/Aviation", label: "Airlines/Aviation" },
  {
    value: "Alternative Dispute Resolution",
    label: "Alternative Dispute Resolution",
  },
  { value: "Alternative Medicine", label: "Alternative Medicine" },
  { value: "Animation", label: "Animation" },
  { value: "Apparel/Fashion", label: "Apparel/Fashion" },
  { value: "Architecture/Planning", label: "Architecture/Planning" },
  { value: "Arts/Crafts", label: "Arts/Crafts" },
  { value: "Automotive", label: "Automotive" },
  { value: "Aviation/Aerospace", label: "Aviation/Aerospace" },
  { value: "Banking/Mortgage", label: "Banking/Mortgage" },
  { value: "Biotechnology/Greentech", label: "Biotechnology/Greentech" },
  { value: "Broadcast Media", label: "Broadcast Media" },
  { value: "Building Materials", label: "Building Materials" },
  {
    value: "Business Supplies/Equipment",
    label: "Business Supplies/Equipment",
  },
  {
    value: "Capital Markets/Hedge Fund/Private Equity",
    label: "Capital Markets/Hedge Fund/Private Equity",
  },
  { value: "Chemicals", label: "Chemicals" },
  { value: "Civic/Social Organization", label: "Civic/Social Organization" },
  { value: "Civil Engineering", label: "Civil Engineering" },
  { value: "Commercial Real Estate", label: "Commercial Real Estate" },
  { value: "Computer Games", label: "Computer Games" },
  { value: "Computer Hardware", label: "Computer Hardware" },
  { value: "Computer Networking", label: "Computer Networking" },
  {
    value: "Computer Software/Engineering",
    label: "Computer Software/Engineering",
  },
  { value: "Computer/Network Security", label: "Computer/Network Security" },
  { value: "Construction", label: "Construction" },
  { value: "Consumer Electronics", label: "Consumer Electronics" },
  { value: "Consumer Goods", label: "Consumer Goods" },
  { value: "Consumer Services", label: "Consumer Services" },
  { value: "Cosmetics", label: "Cosmetics" },
  { value: "Dairy", label: "Dairy" },
  { value: "Defense/Space", label: "Defense/Space" },
  { value: "Design", label: "Design" },
  { value: "E-Learning", label: "E-Learning" },
  { value: "Education Management", label: "Education Management" },
  {
    value: "Electrical/Electronic Manufacturing",
    label: "Electrical/Electronic Manufacturing",
  },
  {
    value: "Entertainment/Movie Production",
    label: "Entertainment/Movie Production",
  },
  { value: "Environmental Services", label: "Environmental Services" },
  { value: "Events Services", label: "Events Services" },
  { value: "Executive Office", label: "Executive Office" },
  { value: "Facilities Services", label: "Facilities Services" },
  { value: "Farming", label: "Farming" },
  { value: "Financial Services", label: "Financial Services" },
  { value: "Fine Art", label: "Fine Art" },
  { value: "Fishery", label: "Fishery" },
  { value: "Food Production", label: "Food Production" },
  { value: "Food/Beverages", label: "Food/Beverages" },
  { value: "Fundraising", label: "Fundraising" },
  { value: "Furniture", label: "Furniture" },
  { value: "Gambling/Casinos", label: "Gambling/Casinos" },
  { value: "Glass/Ceramics/Concrete", label: "Glass/Ceramics/Concrete" },
  { value: "Government Administration", label: "Government Administration" },
  { value: "Government Relations", label: "Government Relations" },
  { value: "Graphic Design/Web Design", label: "Graphic Design/Web Design" },
  { value: "Health/Fitness", label: "Health/Fitness" },
  { value: "Higher Education/Acadamia", label: "Higher Education/Acadamia" },
  { value: "Hospital/Health Care", label: "Hospital/Health Care" },
  { value: "Hospitality", label: "Hospitality" },
  { value: "Human Resources/HR", label: "Human Resources/HR" },
  { value: "Import/Export", label: "Import/Export" },
  { value: "Individual/Family Services", label: "Individual/Family Services" },
  { value: "Industrial Automation", label: "Industrial Automation" },
  { value: "Information Services", label: "Information Services" },
  { value: "Information Technology/IT", label: "Information Technology/IT" },
  { value: "Insurance", label: "Insurance" },
  { value: "International Affairs", label: "International Affairs" },
  {
    value: "International Trade/Development",
    label: "International Trade/Development",
  },
  { value: "Internet", label: "Internet" },
  { value: "Investment Banking/Venture", label: "Investment Banking/Venture" },
  {
    value: "Investment Management/Hedge Fund/Private Equity",
    label: "Investment Management/Hedge Fund/Private Equity",
  },
  { value: "Judiciary", label: "Judiciary" },
  { value: "Law Enforcement", label: "Law Enforcement" },
  { value: "Law Practice/Law Firms", label: "Law Practice/Law Firms" },
  { value: "Legal Services", label: "Legal Services" },
  { value: "Legislative Office", label: "Legislative Office" },
  { value: "Leisure/Travel", label: "Leisure/Travel" },
  { value: "Library", label: "Library" },
  { value: "Logistics/Procurement", label: "Logistics/Procurement" },
  { value: "Luxury Goods/Jewelry", label: "Luxury Goods/Jewelry" },
  { value: "Machinery", label: "Machinery" },
  { value: "Management Consulting", label: "Management Consulting" },
  { value: "Maritime", label: "Maritime" },
  { value: "Market Research", label: "Market Research" },
  {
    value: "Marketing/Advertising/Sales",
    label: "Marketing/Advertising/Sales",
  },
  {
    value: "Mechanical or Industrial Engineering",
    label: "Mechanical or Industrial Engineering",
  },
  { value: "Media Production", label: "Media Production" },
  { value: "Medical Equipment", label: "Medical Equipment" },
  { value: "Medical Practice", label: "Medical Practice" },
  { value: "Mental Health Care", label: "Mental Health Care" },
  { value: "Military Industry", label: "Military Industry" },
  { value: "Mining/Metals", label: "Mining/Metals" },
  { value: "Motion Pictures/Film", label: "Motion Pictures/Film" },
  { value: "Museums/Institutions", label: "Museums/Institutions" },
  { value: "Music", label: "Music" },
  { value: "Nanotechnology", label: "Nanotechnology" },
  { value: "Newspapers/Journalism", label: "Newspapers/Journalism" },
  { value: "Non-Profit/Volunteering", label: "Non-Profit/Volunteering" },
  { value: "Oil/Energy/Solar/Greentech", label: "Oil/Energy/Solar/Greentech" },
  { value: "Online Publishing", label: "Online Publishing" },
  { value: "Other Industry", label: "Other Industry" },
  { value: "Outsourcing/Offshoring", label: "Outsourcing/Offshoring" },
  { value: "Package/Freight Delivery", label: "Package/Freight Delivery" },
  { value: "Packaging/Containers", label: "Packaging/Containers" },
  { value: "Paper/Forest Products", label: "Paper/Forest Products" },
  { value: "Performing Arts", label: "Performing Arts" },
  { value: "Pharmaceuticals", label: "Pharmaceuticals" },
  { value: "Philanthropy", label: "Philanthropy" },
  { value: "Photography", label: "Photography" },
  { value: "Plastics", label: "Plastics" },
  { value: "Political Organization", label: "Political Organization" },
  {
    value: "Primary/Secondary Education",
    label: "Primary/Secondary Education",
  },
  { value: "Printing", label: "Printing" },
  { value: "Professional Training", label: "Professional Training" },
  { value: "Program Development", label: "Program Development" },
  { value: "Public Relations/PR", label: "Public Relations/PR" },
  { value: "Public Safety", label: "Public Safety" },
  { value: "Publishing Industry", label: "Publishing Industry" },
  { value: "Railroad Manufacture", label: "Railroad Manufacture" },
  { value: "Ranching", label: "Ranching" },
  { value: "Real Estate/Mortgage", label: "Real Estate/Mortgage" },
  {
    value: "Recreational Facilities/Services",
    label: "Recreational Facilities/Services",
  },
  { value: "Religious Institutions", label: "Religious Institutions" },
  { value: "Renewables/Environment", label: "Renewables/Environment" },
  { value: "Research Industry", label: "Research Industry" },
  { value: "Restaurants", label: "Restaurants" },
  { value: "Retail Industry", label: "Retail Industry" },
  { value: "Security/Investigations", label: "Security/Investigations" },
  { value: "Semiconductors", label: "Semiconductors" },
  { value: "Shipbuilding", label: "Shipbuilding" },
  { value: "Sporting Goods", label: "Sporting Goods" },
  { value: "Sports", label: "Sports" },
  { value: "Staffing/Recruiting", label: "Staffing/Recruiting" },
  { value: "Supermarkets", label: "Supermarkets" },
  { value: "Telecommunications", label: "Telecommunications" },
  { value: "Textiles", label: "Textiles" },
  { value: "Think Tanks", label: "Think Tanks" },
  { value: "Tobacco", label: "Tobacco" },
  { value: "Translation/Localization", label: "Translation/Localization" },
  { value: "Transportation", label: "Transportation" },
  { value: "Utilities", label: "Utilities" },
  { value: "Venture Capital/VC", label: "Venture Capital/VC" },
  { value: "Veterinary", label: "Veterinary" },
  { value: "Warehousing", label: "Warehousing" },
  { value: "Wholesale", label: "Wholesale" },
  { value: "Wine/Spirits", label: "Wine/Spirits" },
  { value: "Wireless", label: "Wireless" },
  { value: "Writing/Editing", label: "Writing/Editing" },
];
